packageExtensions:
  "pino@*":
    dependencies:
      "pino-pretty": "*"
  "ilp-packet@*":
    dependencies:
      "@types/long": "4.0.1"
      "long": "^4.0.0"
  "@interledger/stream-receiver@*":
    dependencies:
      "ilp-protocol-ildcp": "^2.1.4"
  "@apollo/client@*":
    dependencies:
      "@types/react": "*"
      "react": "*"
  "@interledger/pay@*":
    dependencies:
      "oer-utils": "^5.1.2"
  "ilp-plugin-http@*":
    dependencies:
      "debug": "^3.1.0"

yarnPath: '.yarn/releases/yarn-berry.cjs'
