version: '3'
services:
  peer-auth:
    image: ghcr.io/interledger/rafiki-auth:latest
    build:
      context: ../..
      dockerfile: ./packages/auth/Dockerfile
    restart: always
    networks:
      - local_rafiki
    ports:
      - "4006:3006"
    environment:
      NODE_ENV: development
      AUTH_DATABASE_URL: postgresql://peerauth:peerauth@database/peerauth
      BYPASS_SIGNATURE_VALIDATION: "true"
      AUTH_SERVER_DOMAIN: "http://localhost:4006"
  peer-backend:
    image: ghcr.io/interledger/rafiki-backend:latest
    build:
      context: ../..
      dockerfile: ./packages/backend/Dockerfile
    restart: always
    privileged: true
    ports:
      - "4000:80"
      - "4001:3001"
    networks:
      - local_rafiki
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      ADMIN_PORT: 3001
      CONNECTOR_PORT: 3002
      OPEN_PAYMENTS_PORT: 80
      DATABASE_URL: postgresql://peerbackend:peerbackend@database/peerbackend
      TIGERBEETLE_CLUSTER_ID: 0
      # Tigerbeetle will support DNS in future
      TIGERBEETLE_REPLICA_ADDRESSES: '["10.5.0.50:4342"]'
      NONCE_REDIS_KEY: test
      AUTH_SERVER_GRANT_URL: http://peer-auth:3006
      AUTH_SERVER_INTROSPECTION_URL: http://peer-auth:3006/introspect
      ILP_ADDRESS: test.peer
      STREAM_SECRET: BjPXtnd00G2mRQwP/8ZpwyZASOch5sUXT5o0iR5b5wU=
      ADMIN_KEY: admin
      PUBLIC_HOST: http://peer-backend
      WEBHOOK_URL: http://local-bank/webhooks
      OPEN_PAYMENTS_URL: http://local-bank
      PRICES_URL: http://local-bank/prices
      REDIS_URL: redis://redis:6379/1
      QUOTE_URL: http://local-bank/quote
      BYPASS_SIGNATURE_VALIDATION: "true"
      PAYMENT_POINTER_URL: https://peer-backend/.well-known/pay
  local-bank:
    build:
      context: ../..
      dockerfile: ./packages/mock-account-provider/Dockerfile
    restart: always
    networks:
      - local_rafiki
    ports:
      - '3031:80'
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      PORT: 80
      SEED_FILE_LOCATION: /workspace/seed.peer.yml
    volumes:
      - ./seed.peer.yml:/workspace/seed.peer.yml
    depends_on:
      - peer-backend
networks:
  local_rafiki:
    external: true
