name: "Rafiki Environment Setup"
description: "Sets node version, init pnpm, restore cache"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2
      with:
        version: 7.14.0
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
