on:
  push:
    branches:
      - '!main'
  pull_request:
    types:
      - opened
      - synchronize

name: PR Checks

jobs:
  checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm checks

  backend:
    runs-on: ubuntu-latest
    needs: checkout
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter backend build:deps
      - run: pnpm --filter backend fetch-schemas
      - run: pnpm --filter backend test

  frontend:
    runs-on: ubuntu-latest
    needs: checkout
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter frontend test

  auth:
    runs-on: ubuntu-latest
    needs: checkout
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter auth build:deps
      - run: pnpm --filter auth fetch-schemas
      - run: pnpm --filter auth test
      - name: AsyncAPI extension
        run: |
          echo "{\"extends\":[\"spectral:oas\",\"spectral:asyncapi\"]}" >> .spectral.json
      - name: Validate Open API specs
        run: |
          npx @stoplight/spectral-cli lint ./packages/auth/openapi/id-provider.yaml ./packages/auth/openapi/resource-server.yaml

  openapi:
    runs-on: ubuntu-latest
    needs: checkout
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter openapi test

  mock-account-provider:
    runs-on: ubuntu-latest
    needs: checkout
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter mock-account-provider build

  open-payments:
    runs-on: ubuntu-latest
    needs: checkout
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter openapi build
      - run: pnpm --filter open-payments test

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - backend
      - frontend
      - auth
      - openapi
      - mock-account-provider
      - open-payments
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm build

  all_pr_checks_passed:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - run: echo 'PR Checks Passed'
