on:
  push:
    branches:
    - '!main'
  pull_request:
    types:
      - opened
      - synchronize

name: PR checks

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: yarn install --immutable --immutable-cache

  accounts:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: yarn workspace accounts lint
      - run: yarn workspace accounts format:check
      - run: yarn install --immutable --immutable-cache
      - run: yarn workspace accounts test

  backend:
    runs-on: ubuntu-latest
    needs: checkout
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: yarn workspace backend lint
      - run: yarn workspace backend format:check
      - run: packages/backend/scripts/init.sh
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgresql://postgres:password@localhost:5432
      - run: yarn workspace backend test

  connector:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: yarn workspace connector lint
      - run: yarn workspace connector format:check
      - run: yarn install --immutable --immutable-cache
      - run: yarn build
      - run: yarn workspace connector test

  frontend:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: yarn workspace frontend lint
      - run: yarn workspace frontend format:check
      - run: yarn workspace frontend test

  build:
    runs-on: ubuntu-latest
    needs:
      - accounts
      - backend
      - connector
      - frontend
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: yarn install --immutable --immutable-cache
      - run: yarn build
