on:
  push:
    branches:
    - '!main'
  pull_request:
    types:
      - opened
      - synchronize

name: PR checks

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: yarn install --immutable --immutable-cache

  backend:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: yarn workspace backend lint
      - run: yarn workspace backend format:check
      - run: yarn workspace backend test

  interledger:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: yarn workspace interledger lint
      - run: yarn workspace interledger format:check
      - run: yarn install --immutable --immutable-cache
      - run: yarn build
      - run: yarn workspace interledger test

  frontend:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: yarn workspace frontend lint
      - run: yarn workspace frontend format:check
      - run: yarn workspace frontend test

  rates:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: yarn workspace rates lint
      - run: yarn workspace rates format:check
      - run: yarn workspace rates test

  build:
    runs-on: ubuntu-latest
    needs:
      - backend
      - interledger
      - frontend
      - rates
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: yarn install --immutable --immutable-cache
      - run: yarn build
