on:
  push:
    branches:
      - '!main'
  pull_request:
    types:
      - opened
      - synchronize

name: PR Checks

jobs:
  checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm checks

  backend:
    runs-on: ubuntu-latest
    needs: checkout
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter backend build:deps
      - run: pnpm --filter backend test

  frontend:
    runs-on: ubuntu-latest
    needs: checkout
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter frontend test

  auth:
    runs-on: ubuntu-latest
    needs: checkout
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter auth build:deps
      - run: pnpm --filter auth test
      - name: AsyncAPI extension
        run: |
          echo "{\"extends\":[\"spectral:oas\",\"spectral:asyncapi\"]}" >> .spectral.json
      - name: Validate Open API specs
        run: |
          npx @stoplight/spectral-cli lint ./packages/auth/openapi/*.yaml

  openapi:
    runs-on: ubuntu-latest
    needs: checkout
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter openapi test

  mock-account-provider:
    runs-on: ubuntu-latest
    needs: checkout
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter mock-account-provider build

  open-payments:
    runs-on: ubuntu-latest
    needs: checkout
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter open-payments build:deps
      - run: pnpm --filter open-payments test
      - name: AsyncAPI extension
        run: |
          echo "{\"extends\":[\"spectral:oas\",\"spectral:asyncapi\"]}" >> .spectral.json
      - name: Validate Open API specs
        run: |
          npx @stoplight/spectral-cli lint ./packages/open-payments/openapi/*.yaml

  http-signature-utils:
    runs-on: ubuntu-latest
    needs: checkout
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter http-signature-utils test

  token-introspection:
    runs-on: ubuntu-latest
    needs: checkout
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter token-introspection build:deps
      - run: pnpm --filter token-introspection test
      - name: AsyncAPI extension
        run: |
          echo "{\"extends\":[\"spectral:oas\",\"spectral:asyncapi\"]}" >> .spectral.json
      - name: Validate Open API specs
        run: |
          npx @stoplight/spectral-cli lint ./packages/token-introspection/openapi/*.yaml

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - backend
      - frontend
      - auth
      - openapi
      - mock-account-provider
      - open-payments
      - http-signature-utils
      - token-introspection
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm build

  all_pr_checks_passed:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - run: echo 'PR Checks Passed'
