# Sanity check on merges with main.
# TODO: Use this workflow for publishing main
on:
  push:
    branches:
    - main
  pull_request:
    types:
      - opened
      - synchronize

name: Sanity check

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: packages/connector/scripts/init.sh
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgresql://postgres:password@localhost:5432
      # NB: --check-cache is an important security check, see https://yarnpkg.com/features/zero-installs#does-it-have-security-implications
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn lint
      - run: yarn build
      - run: yarn test
